[project]
authors = ["yl <2201441955@qq.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly", "https://repo.prefix.dev/better-ffi"]
description = "Add a short description here"
name = "sonic-mojo"

platforms = ["linux-64", "osx-arm64"]

version = "0.1.0"

[tasks]
build-mojo = { cmd = "rattler-build build --recipe recipes/mojo-recipe.yaml -c https://conda.modular.com/max -c conda-forge --skip-existing=all" }
build-rs = { cmd = "rattler-build build --recipe recipes/rs-recipe.yaml -c https://conda.modular.com/max -c conda-forge --skip-existing=all" }

[dependencies]
max = ">=24.6.0.dev2024102905,<25"

[feature.dev.dependencies]
rust = "*"
