[project]
authors = ["hhglory <hhglory@outlook.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly", "https://repo.prefix.dev/better-ffi", "https://repo.prefix.dev/better-mojo-nightly"]

description = "Add a short description here"
name = "try-sonic"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.5.0,<25"
sonic_mojo = ">=0.1.1,<0.2"
libsonic = ">=0.1.1,<0.2"
